### ISSUE TITLE
Please, rename plugin

### ISSUE THREAD

**Issue by Hitman477** [Ajneb97/Codex#14]
Good afternoon. I ran into the following problem - I am developing an RPG project, and I came across your plugin. I really liked it and I put it on. But there was a conflict with another plugin with the same name from another developer. Please tell me, is it possible to rename the plugin somehow so that there are no similar problems?

error text [12:18:09] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Ambiguous plugin name 'Code' for files 'plugins\Codex.jar' and 'plugins\codex-1.0.0-R0.17-20240605.061412-1.jar' in 'plugins'

**Comment by Amgelo563** [comment]
I think you should be able to change either of the plugin's name by opening the jar as a zip file and editing the `name` property on the `plugin.yml` file.

**Comment by Hitman477** [comment]
i renamed plugins name and commands for sure. Sry for interruption.
