### ISSUE TITLE
[ISSUE] Regions not shown

### ISSUE THREAD

**Issue by Fer-Jg** [Ajneb97/Codex#2]
When a third region (or more) is set in the config (`Codex/categories/regions.yml`) it does not work in game, the categories menu shows the correct amount of available discoveries but once you go into the Regions category, only 2 discoveries show up, this kind of makes the plugin unusable since that is basically a core feature needed for an RPG-like experience.

**Codex version: 1.12.1**
**Server version: Purpur 1.19.2**

P.S. If you need any help with the code I would love to contribute, just let me know and walk me through your code and I will do as much as I can :)

P.S.2. You should make your code in english if you are planning on sharing it on github for contributions/feedback/whatever, that way more people can understand it :)

**Comment by Ajneb97** [comment]
You must add the discovery yourself on the inventory.yml file.

**Comment by Fer-Jg** [comment]
True, thanks for the info hehe
